only make 'python setup.py' commands fail in checks for create_source_tarball.sh script

diff --git a/.github/workflows/scripts.yml b/.github/workflows/scripts.yml
--- a/.github/workflows/scripts.yml
+++ b/.github/workflows/scripts.yml
@@ -100,23 +100,36 @@ jobs:
         
         echo "================================================================================================"
 
-        # script should fail if expected source tarball did not get created in dist/
+        # create fake 'python' command:
+        # just exits when 1st argument is setup.py, but calls out to origin Python command otherwise;
+        # this is important w.r.t. the Python version checks run by the 'eb' script
         mkdir -p /tmp/$USER/bin
+        export PATH=/tmp/$USER/bin:$PATH
         echo '#!/bin/bash' > /tmp/$USER/bin/python
         chmod u+x /tmp/$USER/bin/python
-        export PATH=/tmp/$USER/bin:$PATH
+        echo 'orig_python=$(which -a python | head -2 | tail -1)' >> /tmp/$USER/bin/python
+        echo 'if [[ "$1" == "setup.py" ]]; then exit 0; else $orig_python "$@"; fi' >> /tmp/$USER/bin/python
+
+        # script should fail if expected source tarball did not get created in dist/
         ($GITHUB_WORKSPACE/scripts/create_source_tarball.sh ${{matrix.repo}} $version 2>&1 | tee $out) || true
         grep "ERROR: Expected file dist/${{matrix.repo}}-${version}.tar.gz not found!" $out
         echo "Expected error found in output: OK!"
+
+        # clean up index file, to avoid check for dirty working directory failing
+        rm -f easybuild/easyconfigs/.eb-path-index
         
         echo "================================================================================================"
 
+        # make fake python command fail if 1st argument is setup.py
+        sed -i 's/exit 0/exit 1/g' /tmp/$USER/bin/python
+
         # script should deal well with failing 'python setup.py sdist'
-        echo 'exit 1' >> /tmp/$USER/bin/python
         ($GITHUB_WORKSPACE/scripts/create_source_tarball.sh ${{matrix.repo}} $version 2>&1 | tee $out) || true
         grep "ERROR: Creating source tarball failed" $out
         echo "Expected error found in output: OK!"
-        rm /tmp/$USER/bin/python
+
+        # cleanup
+        rm -f /tmp/$USER/bin/python easybuild/easyconfigs/.eb-path-index
         
         echo "================================================================================================"
 
